 # NUMPY Z KURSU

**Numpy** opiera się na tabelach `arrays`. Powstały one do obliczeń matematycznych. Przypominają listy, ale wspomagają grupowe operacje matematyczne będące operacjami w `Numpy`.

In [1]:
import numpy as np

In [2]:
distance = [10, 15, 17, 26]
time = [.30, .47, .55, 1.20]

In [4]:
np_distance = np.array(distance)
np_time = np.array(time)
speed = np_distance/np_time

In [5]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

`ndarray` na których opiera się Numpy cechuje się tym, że:
- jest kontenerem wartości
- jest homogeniczny tj. posiada tylko jeden typ danych w sobie
- można na nim operować normalnie, jak na liście tj. dodawać elementy, usumować, zmieniać...
- szybki i wydajny
- wspiera operacje matematyczne
- może być wielowymiarowy

In [6]:
#first NumPy array
firstNpArray = np.array([1,2,3,4])

#printing
print(firstNpArray)

[1 2 3 4]


In [7]:
#array with zeros
arrayWithZeros = np.zeros((3,3))
arrayWithZeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#array with ones
arrayWithOnes = np.ones((3,3))
arrayWithOnes

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
#array with empty
arrayWithEmpty = np.empty((2,4))
arrayWithEmpty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.62047965e-321, 8.90104238e-307,
        1.24610383e-306]])

In [13]:
#array with arange method
npArange = np.arange(12)
print( npArange )

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
#reshape:
npArange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
#linspace for linearly spaced data elements
npLinear = np.linspace(1,6,5) #1 - wartość elementu pierwszego, 6 - wartość elementu ostatniego, 5 - ilość elementów

In [18]:
print(npLinear)

[1.   2.25 3.5  4.75 6.  ]


In [20]:
#One dimensional array
oneDArray = np.arange(15)
#reshape into 2D
twoDAttay = oneDArray.reshape(3,5)

print(twoDAttay)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
#three dimensional array
threeDArray = np.arange(27).reshape(3,3,3)
print(threeDArray)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


**Metody ndarray opisujące zawartość tablicy**

In [24]:
#stworzenie przykładowej ndarray:
Parray = np.array([[1,5,11,3,32,1],[4,3,2,5,4,1]])

- `ndarray.ndim`:

In [25]:
#liczba wymiarów
print(Parray.ndim)

2


- `ndarray.shape`:

In [27]:
#kształt:
print(Parray.shape)

(2, 6)


- `ndarray.size`:

In [28]:
#rozmiar
print(Parray.size)

12


- `ndarray.dtype`:

In [29]:
#typ danych
print(Parray.dtype)

int32


**Operacje arytmetyczne na tablicach**

In [30]:
#utworzenie tablic
pierwszaAr = np.array([1,11,111,2,22,222])
drugaAr = np.array([3,33,333,44,44,444])

In [31]:
#dodawanie:
print( pierwszaAr + drugaAr )

[  4  44 444  46  66 666]


In [32]:
#odejmowanie:
print( drugaAr - pierwszaAr )

[  2  22 222  42  22 222]


In [33]:
#mnożenie dwóch wektorów:
print( pierwszaAr * drugaAr )

[    3   363 36963    88   968 98568]


In [35]:
#mnożenie przez skalar:
print( 5 * pierwszaAr )

[   5   55  555   10  110 1110]


In [36]:
#podliczenie wektora:
print( drugaAr.sum() )

901


In [38]:
#lub..... 
print( sum(drugaAr) )

901


**Operacje porównania na tablicach oraz indeksowanie wartościami logicznymi typu bool**

In [40]:
#proste porównanie 
print(pierwszaAr > 20)

[False False  True False  True  True]


In [42]:
#sprawdzenie, które wartości spełniają warunek:
pierwszaAr[ pierwszaAr > 20 ]

array([111,  22, 222])

**Operacje logiczne na tablicach**

In [45]:
#dla wartości różnych od zera jest True
np.logical_and(pierwszaAr, drugaAr)

array([ True,  True,  True,  True,  True,  True])

**Dzielenie tablic - slicing**

# Funkcje matematyczne na tablicach

`Numpy` dostarcza szereg uniwersalnych funkcji matematycznych np.:
- `cos` kosinus dla każdego elementu tablicy
- `exp` eksponenta dla każdego elementu tablicy
- `floor` zwraca największą wartość całkowitą dla każdego elementu tabeli
- `sqrt` wiadomo - pierwiastek

In [46]:
#floor
np.floor( [ 1.9, 2.4, -0.3, 5.1 ] )

array([ 1.,  2., -1.,  5.])

**Operacje na rozmiarach tablicy**

In [53]:
#stworzenie przykładowej tablicy:
przykladowa = np.array([[10,17,55,23,14,29],[92,14,54,34,23,33]])
print(przykladowa)

[[10 17 55 23 14 29]
 [92 14 54 34 23 33]]


- `ravel`:

In [51]:
#spłaszczanie danych:
print(przykladowa.ravel())

[10 17 55 23 14 29 92 14 54 34 23 33]


In [52]:
#warto zwrócić uwagę na to, że nie wpływa na oryginalną tablicę:
print(przykladowa)

[[10 17 55 23 14 29]
 [92 14 54 34 23 33]]


- `reshape`:

In [58]:
#zwrócenie przekształconej tabeli
print(przykladowa.reshape(3,4))

[[10 17 55 23]
 [14 29 92 14]
 [54 34 23 33]]


In [59]:
#bez wpływu na oryginał
print(przykladowa)

[[10 17 55 23]
 [14 29 92 14]
 [54 34 23 33]]


- `resize`:

In [63]:
#zmiana oryginału
print(przykladowa.resize(3,4))

None


In [64]:
print(przykladowa)

[[10 17 55 23]
 [14 29 92 14]
 [54 34 23 33]]


- `hsplit`:

In [67]:
#podział w pionie
podprzyklad1, podprzyklad2 = np.hsplit(przykladowa,2)

In [68]:
print(podprzyklad1)

[[10 17]
 [14 29]
 [54 34]]


In [69]:
print(podprzyklad2)

[[55 23]
 [92 14]
 [23 33]]


- `hstack`:

In [71]:
#połączenie:
powrot = np.hstack([podprzyklad1, podprzyklad2]) #<- tu może być też tupla, nie musi być lista

In [72]:
print(powrot)

[[10 17 55 23]
 [14 29 92 14]
 [54 34 23 33]]


**Transpozycja**

In [73]:
print(przykladowa)

[[10 17 55 23]
 [14 29 92 14]
 [54 34 23 33]]


In [74]:
print(przykladowa.transpose())

[[10 14 54]
 [17 29 34]
 [55 92 23]
 [23 14 33]]


**Inwersja**

In [76]:
#przykladowa macierz kwadratowa
kwadrat = np.array([[10,20],[15,25]])
print(np.linalg.inv(kwadrat))

[[-0.5  0.4]
 [ 0.3 -0.2]]


**Suma elementów po przekątnej**

In [77]:
print(np.trace(kwadrat)) #w tym przypadku 10 + 25

35
