# KNN K nearest neighbours

main formula for k: <br />
$k = \sqrt{2n-1}$

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
dataset = pd.read_csv('Social_Network_ads.csv')
print(dataset)
X = dataset.iloc[:,:-1].values #independent
y = dataset.iloc[:,-1].values #dependent

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]


In [14]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer( missing_values= np.nan, strategy = 'mean')
imputer.fit(X)
X = imputer.transform(X)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state=2 )

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# zastosowanie formuły na k:

In [30]:
np.sqrt(2*len(X_test)-1) 

12.609520212918492

In [37]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier( n_neighbors=13, metric='minkowski', p=2) # tu to 13 to z powyższego; p=2 euklidian/p=1 manhattan
classifier.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [38]:
print(classifier.predict(sc.transform([[35,88000]])))

[0]


In [39]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]]


In [40]:
#confision matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix( y_test, y_pred )
print(cm)

[[46  2]
 [ 5 27]]


In [41]:
accuracy_score(y_test,y_pred )

0.9125

# Inne dane: Cancer cell data

In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


dataset = pd.read_csv('CANCER CELL DATA.csv')
#print(dataset)

In [47]:
X = dataset.iloc[:,2:].values #independent

y = dataset.iloc[:,1].values #dependent

In [48]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer( missing_values= np.nan, strategy = 'mean')
imputer.fit(X)
X = imputer.transform(X)

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state=2 )

In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [52]:
np.sqrt(2*len(X_test)-1)

15.066519173319364

In [63]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier( n_neighbors=15, metric='minkowski', p=2) # tu to 15 to z powyższego; p=2 euklidian/p=1 manhattan
classifier.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [64]:
y_pred = classifier.predict(X_test)

In [65]:
#confision matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix( y_test, y_pred )
print(cm)

accuracy_score(y_test,y_pred )

[[69  0]
 [ 4 41]]


0.9649122807017544

# dla 3 jest lepszy model, bo daje 99,1%

In [77]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier( n_neighbors=3, metric='minkowski', p=2) # tu to 15 to z powyższego; p=2 euklidian/p=1 manhattan
classifier.fit(X_train,y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix( y_test, y_pred )
print(cm)

accuracy_score(y_test,y_pred )

[[69  0]
 [ 1 44]]


0.9912280701754386

# NAIVE BAYES



In [87]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


dataset = pd.read_csv('Social_Network_Ads.csv')
#print(dataset)

In [88]:
X = dataset.iloc[:,:-1].values #independent
y = dataset.iloc[:,-1].values #dependent

In [89]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer( missing_values= np.nan, strategy = 'mean')
imputer.fit(X)
X = imputer.transform(X)

In [90]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state=2 )

In [91]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [92]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

In [94]:
y_pred = classifier.predict(X_test)

In [95]:
#confision matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix( y_test, y_pred )
print(cm)

accuracy_score(y_test,y_pred )

[[46  2]
 [10 22]]


0.85

# Decision tree and random forest regression


In [104]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


dataset = pd.read_csv('Social_Network_Ads.csv')
#print(dataset)
X = dataset.iloc[:,:-1].values #independent
y = dataset.iloc[:,-1].values #dependent

from sklearn.impute import SimpleImputer
imputer = SimpleImputer( missing_values= np.nan, strategy = 'mean')
imputer.fit(X)
X = imputer.transform(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state=2 )

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [105]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [106]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix( y_test, y_pred )
print(cm)

accuracy_score(y_test,y_pred )

[[43  5]
 [ 7 25]]


0.85

# Forest:

In [123]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


dataset = pd.read_csv('Social_Network_Ads.csv')
#print(dataset)
X = dataset.iloc[:,:-1].values #independent
y = dataset.iloc[:,-1].values #dependent

from sklearn.impute import SimpleImputer
imputer = SimpleImputer( missing_values= np.nan, strategy = 'mean')
imputer.fit(X)
X = imputer.transform(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state=2 )

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [124]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier( n_estimators = 10 )
classifier.fit(X_train,y_train)

RandomForestClassifier(n_estimators=10)

In [125]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix( y_test, y_pred )
print(cm)

accuracy_score(y_test,y_pred )

[[44  4]
 [ 4 28]]


0.9