# 27.06


 **NumPy**

In [24]:
import numpy as np
a = np.array([[1,2],
              [3,4]])
b = np.array([[4,3],
              [2,1]])

a*b #<-elementy się przemnażają względem odpowiednich w drugiej macierzy

array([[4, 6],
       [6, 4]])

In [8]:
a.dot(b) #mnożenie wektorami, czyli to, jak wiem jak

array([[ 8,  5],
       [20, 13]])

In [26]:
b.ndim #amount of dimensions

2

In [27]:
type(b)

numpy.ndarray

In [28]:
b.shape #the shape in eash dimension

(2, 2)

In [29]:
b.size #how many elements

4

In [12]:
z = np.array(['1','2'], np.float64)
z

array([1., 2.])

In [13]:
z.dtype

dtype('float64')

In [14]:
stringArray = np.array(['1','2'])
stringArray.dtype

dtype('<U1')

In [17]:
y = np.array([1,5], dtype='<U1')
print(y)
y.dtype

['1' '5']


dtype('<U1')

In [18]:
y.astype(np.float)

array([1., 5.])

In [32]:
#duża macierz:

ma = np.array([[-1,2,0,4],
               [4,-0.5,6,0],
               [2.6,0,7,8],
               [3,-7,4,2]])
print(type(ma))
print(ma.size)
print(ma.shape)
print(ma.ndim)

tmp = ma[:2,::2]
print(tmp)

<class 'numpy.ndarray'>
16
(4, 4)
2
[[-1.  0.]
 [ 4.  6.]]


In [33]:
ma > 2

array([[False, False, False,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True, False]])

In [34]:
ma[ma>2]

array([4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. ])

In [36]:
len(ma[ma>2])

8

In [44]:
for i in np.nditer(ma):
    print(i)

-1.0
2.0
0.0
4.0
4.0
-0.5
6.0
0.0
2.6
0.0
7.0
8.0
3.0
-7.0
4.0
2.0


In [45]:
np.linalg.matrix_rank(ma)

4

In [46]:
np.trace(ma)

7.5

In [47]:
np.diag(ma)

array([-1. , -0.5,  7. ,  2. ])

In [50]:
#wyznacznik macierzy
np.linalg.det(ma)

-80.59999999999995

In [51]:
#odwrócenie macierzy:
np.linalg.inv(ma)

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

In [53]:
np.linalg.matrix_rank(ma)

4

In [54]:
np.linalg.matrix_power(ma,3)

array([[ -60.2  ,   29.5  ,   26.   ,  316.   ],
       [ 316.8  , -432.925,  578.5  ,  478.4  ],
       [ 215.   , -472.2  ,  591.8  ,  971.2  ],
       [ 125.   , -362.95 ,  123.   ,  -10.4  ]])

# Scikit-learn





In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import sklearn 

In [66]:
dataset = pd.DataFrame({'Country':['France','Germany','Spain','France','Germany','Spain','France','Germany'],
                        'Age':[22,34,25,None,25,26,28,29],
                        'Salary':[72000,81000,10000,15000,None,17000,19000,22000],
                        'Purchased':['Yes','No','Yes','No','Yes','No','Yes','No']})
dataset

Country   Age   Salary Purchased
0   France  22.0  72000.0       Yes
1  Germany  34.0  81000.0        No
2    Spain  25.0  10000.0       Yes
3   France   NaN  15000.0        No
4  Germany  25.0      NaN       Yes
5    Spain  26.0  17000.0        No
6   France  28.0  19000.0       Yes
7  Germany  29.0  22000.0        No

Independent variables: **Country**, **Ages**, **Salary**  *<- base on which we want to predict*

Dependent variables: **Purchased** *<- parameter to predict*



In [101]:
X = dataset.iloc[:,:-1].values #everything except the last column with dependent variable
print(X)
print("\n"+str(type(X)))

[['France' 22.0 72000.0]
 ['Germany' 34.0 81000.0]
 ['Spain' 25.0 10000.0]
 ['France' nan 15000.0]
 ['Germany' 25.0 nan]
 ['Spain' 26.0 17000.0]
 ['France' 28.0 19000.0]
 ['Germany' 29.0 22000.0]]

<class 'numpy.ndarray'>


In [102]:
Xx = dataset.iloc[:,:-1]
Xx

Country   Age   Salary
0   France  22.0  72000.0
1  Germany  34.0  81000.0
2    Spain  25.0  10000.0
3   France   NaN  15000.0
4  Germany  25.0      NaN
5    Spain  26.0  17000.0
6   France  28.0  19000.0
7  Germany  29.0  22000.0

In [103]:
Y = dataset.iloc[:,-1].values
Y

array(['Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'], dtype=object)

# taking care of missing values:

methods inside sklearn: `Fit`  and  `fit_transform`

In [104]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer( missing_values = np.nan, strategy = 'mean' )
imputer.fit(X[:,1:3])
X #nic nie jest zmienione jeszcze

array([['France', 22.0, 72000.0],
       ['Germany', 34.0, 81000.0],
       ['Spain', 25.0, 10000.0],
       ['France', nan, 15000.0],
       ['Germany', 25.0, nan],
       ['Spain', 26.0, 17000.0],
       ['France', 28.0, 19000.0],
       ['Germany', 29.0, 22000.0]], dtype=object)

In [105]:
X[:,1:3] = imputer.transform(X[:,1:3]) #dopiero ta metoda zamienia
X[:,1:3]

array([[22.0, 72000.0],
       [34.0, 81000.0],
       [25.0, 10000.0],
       [27.0, 15000.0],
       [25.0, 33714.28571428572],
       [26.0, 17000.0],
       [28.0, 19000.0],
       [29.0, 22000.0]], dtype=object)

In [106]:
X

array([['France', 22.0, 72000.0],
       ['Germany', 34.0, 81000.0],
       ['Spain', 25.0, 10000.0],
       ['France', 27.0, 15000.0],
       ['Germany', 25.0, 33714.28571428572],
       ['Spain', 26.0, 17000.0],
       ['France', 28.0, 19000.0],
       ['Germany', 29.0, 22000.0]], dtype=object)

In [88]:
print(Xx['Age'].mean()) 
print(Xx['Salary'].mean())

27.0
33714.28571428572


**To samo można zrobić w jednej funkcji: fit_transform()**

In [97]:
Xft = imputer.fit_transform(X[:,1:3])
Xft

array([[2.20000000e+01, 7.20000000e+04],
       [3.40000000e+01, 8.10000000e+04],
       [2.50000000e+01, 1.00000000e+04],
       [2.70000000e+01, 1.50000000e+04],
       [2.50000000e+01, 3.37142857e+04],
       [2.60000000e+01, 1.70000000e+04],
       [2.80000000e+01, 1.90000000e+04],
       [2.90000000e+01, 2.20000000e+04]])

# One hot encoding for indepedent variable

czyli 1 z n:
K1 | K2 | K3
 0 | 0  | 1
 0 | 1  | 0
 1 | 0  | 0

In [107]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer( transformers = [('encoder', OneHotEncoder(), [0] )], remainder = 'passthrough' )
X = np.array( ct.fit_transform(X) )
print(X)

array([[1.0, 0.0, 0.0, 22.0, 72000.0],
       [0.0, 1.0, 0.0, 34.0, 81000.0],
       [0.0, 0.0, 1.0, 25.0, 10000.0],
       [1.0, 0.0, 0.0, 27.0, 15000.0],
       [0.0, 1.0, 0.0, 25.0, 33714.28571428572],
       [0.0, 0.0, 1.0, 26.0, 17000.0],
       [1.0, 0.0, 0.0, 28.0, 19000.0],
       [0.0, 1.0, 0.0, 29.0, 22000.0]], dtype=object)

Jak widać pierwsza kolumna została zamieniona na trzy, pozostałe zostały przepisane ('passthrough')

# label encoding in the dependent variable:

In [110]:
#label encoding in the dependent variable:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
Y

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

# Spliting into test and train


**split ratio** can vary from 80% to 66% for training set, and respectively 20-33% for test
The method below choose the data randomly base on `random_state`

In [173]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size = 0.2, random_state = 1 ) #random assignment by choosing random_state

In [174]:
X_train

array([[0.0, 1.0, 0.0, 34.0, 81000.0],
       [1.0, 0.0, 0.0, 28.0, 19000.0],
       [1.0, 0.0, 0.0, 22.0, 72000.0],
       [0.0, 1.0, 0.0, 25.0, 33714.28571428572],
       [1.0, 0.0, 0.0, 27.0, 15000.0],
       [0.0, 0.0, 1.0, 26.0, 17000.0]], dtype=object)

In [175]:
X_test

array([[0.0, 1.0, 0.0, 29.0, 22000.0],
       [0.0, 0.0, 1.0, 25.0, 10000.0]], dtype=object)

In [176]:
Y_train

array([0, 1, 1, 1, 0, 0], dtype=int64)

In [177]:
Y_test

array([0, 1], dtype=int64)

In [178]:
X_test

array([[0.0, 1.0, 0.0, 29.0, 22000.0],
       [0.0, 0.0, 1.0, 25.0, 10000.0]], dtype=object)

In [179]:
X_test[ :, 3: ]

array([[29.0, 22000.0],
       [25.0, 10000.0]], dtype=object)

# Feature scaling

Two main methods:
Normalization: x_new = ( x_old - x_min ) / ( x_max - x_min )
Standarization: x_new = ( x_old - mean ) / std

**for 90% it's better to choose standarization!!!!** It is the advice, but it is like that.
And one method for all column

In [180]:
#standarisation
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform( X_train[ :, 3: ] ) # <-- omiting one hot coding columns
X_test[:,3:] = sc.transform( X_test[ :, 3: ] ) # <-- only transform (we are keeping the fitted values)

print(X_train)
print(X_test)

[[0.0 1.0 0.0 1.9170289512680814 1.5388607622754311]
 [1.0 0.0 0.0 0.27386127875258304 -0.7667741197528903]
 [1.0 0.0 0.0 -1.3693063937629153 1.2041718277874491]
 [0.0 1.0 0.0 -0.5477225575051661 -0.21958427447888762]
 [1.0 0.0 0.0 0.0 -0.9155247573031046]
 [0.0 0.0 1.0 -0.27386127875258304 -0.8411494385279974]]
[[0.0 1.0 0.0 0.5477225575051661 -0.6552111415902295]
 [0.0 0.0 1.0 -0.5477225575051661 -1.1014630542408725]]


In [157]:
X_test

array([[0.0, 1.0, 0.0, 1.0, 1.0],
       [0.0, 0.0, 1.0, -1.0, -1.0]], dtype=object)

In [181]:
#normalisation:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
X_train[:,3:] = sc.fit_transform( X_train[ :, 3: ] ) # <-- omiting one hot coding columns
X_test[:,3:] = sc.transform( X_test[ :, 3: ] ) # <-- only transform (we are keeping the fitted values)

print(X_train)
print(X_test)

[[0.0 1.0 0.0 1.9170289512680814 1.5388607622754311]
 [1.0 0.0 0.0 0.27386127875258304 -0.7667741197528903]
 [1.0 0.0 0.0 -1.3693063937629153 1.2041718277874491]
 [0.0 1.0 0.0 -0.5477225575051661 -0.21958427447888768]
 [1.0 0.0 0.0 1.850371707708594e-17 -0.9155247573031047]
 [0.0 0.0 1.0 -0.27386127875258304 -0.8411494385279974]]
[[0.0 1.0 0.0 0.5477225575051661 -0.6552111415902295]
 [0.0 0.0 1.0 -0.5477225575051661 -1.1014630542408725]]
